# Generated by Django 4.2.5 on 2023-10-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
