# Generated by Django 4.2.5 on 2023-10-17 12:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Содержимое статьи')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Изображение')),
                ('creation_date', models.DateTimeField(default=blog.models.default_datetime, verbose_name='Дата публикации')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
