# Generated by Django 4.2.5 on 2023-10-10 17:48

from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Тема рассылки')),
                ('body', models.TextField(verbose_name='Тело письма')),
                ('time', models.DateTimeField(default=service.models.default_datetime, verbose_name='Дата создания')),
                ('period', models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=10, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('finished', 'завершена'), ('created', 'создана'), ('started', 'запущена')], default='создана', max_length=10, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=service.models.default_datetime, verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(choices=[('Not_sent', 'Не отправлено'), ('Departure', 'Отправляется'), ('Sent', 'Отправлено')], max_length=10, verbose_name='Статус попытки')),
                ('period', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ почтового сервиса')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.mailing', verbose_name='Тема рассылки')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
