# Generated by Django 4.2.5 on 2023-10-19 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 11, 6, 34, 942091, tzinfo=datetime.timezone.utc), verbose_name='Время начала'),
        ),
    ]
