# Generated by Django 4.2.5 on 2023-10-22 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='service.client'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 7, 49, 55, 244200, tzinfo=datetime.timezone.utc), verbose_name='Время начала'),
        ),
    ]
