# Generated by Django 4.2.5 on 2023-10-13 21:32

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_logs_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(blank=True, default=service.models.default_datetime, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.DateTimeField(blank=True, default=service.models.default_datetime, null=True, verbose_name='Дата создания'),
        ),
    ]
