# Generated by Django 4.2.5 on 2023-10-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_mailing_clients_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время начала'),
        ),
    ]
