# Generated by Django 4.2.5 on 2023-10-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Отметка об активности'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='service.client', verbose_name='Клиенты'),
        ),
    ]
