# Generated by Django 4.2.5 on 2023-10-13 21:38

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_time',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=service.models.default_datetime, verbose_name='Время начала'),
        ),
    ]
