# Generated by Django 4.2.5 on 2023-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_client_user_mailing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('finished', 'завершена'), ('created', 'создана'), ('started', 'запущена')], default='created', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
