# Generated by Django 4.2.5 on 2023-10-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, to='service.client'),
        ),
    ]
