# Generated by Django 4.2.5 on 2023-10-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Статус рассылки'),
        ),
    ]
