# Generated by Django 4.2.5 on 2023-10-23 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 11, 19, 8, 698992), verbose_name='Время начала'),
        ),
    ]
