# Generated by Django 4.2.5 on 2023-10-24 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_alter_mailing_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='period',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 8, 59, 53, 928607), verbose_name='Время начала'),
        ),
    ]
