# Generated by Django 4.2.5 on 2023-10-24 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_alter_logs_email_alter_logs_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(max_length=10, verbose_name='Статус попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 9, 17, 9, 155369), verbose_name='Время начала'),
        ),
    ]
