# Generated by Django 4.2.5 on 2023-10-24 07:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_alter_logs_title_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.mailing', verbose_name='Тема рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 9, 56, 42, 124460), verbose_name='Время начала'),
        ),
    ]
