# Generated by Django 4.2.5 on 2023-10-24 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_alter_logs_title_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тема рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 10, 3, 45, 826860), verbose_name='Время начала'),
        ),
    ]
