# Generated by Django 4.2.5 on 2023-10-30 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0037_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 21, 0, 8, 561783), verbose_name='Время начала'),
        ),
    ]
