# Generated by Django 4.2.5 on 2023-10-31 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 8, 0, 33, 63985), verbose_name='Время начала'),
        ),
    ]
